export const GET_POST_REQUIRED = "GET_POST_REQUIRED";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const REMOVE_POST_SUCCESS = "REMOVE_POST";
export const REMOVE_POST_FAIL = "REMOVE_POST";